### ISSUE TITLE
Bug and Questions (BRAT/Community Plugin)

### ISSUE THREAD

**Issue by lifehaschanged** [Fevol/obsidian-criticmarkup#18]
When this Plugin is installed with BRAT (sandbox vault without any other plugins than BRAT):
https://github.com/TfTHacker/obsidian42-brat

It's causing many errors and showing me no sidebars and commands:

![grafik](https://github.com/Fevol/obsidian-criticmarkup/assets/81463128/e647e392-8fbe-4adb-8bf7-7853eadd5a6f)

Do you plan to make this plugin available for BRAT / Community Plugin store inside Obsidian?

**Comment by Fevol** [comment]
Addendum, potentially related to #16

**Comment by javiavid** [comment]
I can't start the plugin either, I get the error message when trying to activate the plugin.
Fails to load plugin "commentator"

SYSTEM INFO:
	Obsidian version: v1.7.3
	Installer version: v1.6.7
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 3
		1: BRAT v1.0.2
		2: Diarian v1.2.9
		3: Banners v1.3.3

**Comment by AlexanderPuzanov** [comment]
Version 0.2.0 does not start.
Version 0.1.4 works.

Empty new storage.
Default theme.
All built-in and community plugins are disabled.

Obsidian version: v1.7.7
Installer version: v1.4.13
OS: Windows 10 Pro

**Comment by Fevol** [comment]
> Once the plugin is deactivated, it cannot be activated again.

Could you share a bit of information on what version of Obsidian is installed, what version of the plugin you are using, and what is in the error log (F12)?

**Comment by davidszp** [comment]
Confirming that after successful installation with BRAT I had to restart Obsidian for obsidian-criticmarkup to load and function correctly.

**Comment by nanjingman** [comment]
The problem was solved after I moved all files and folders under .obsidian, except the plugins folder. For your reference.

**Comment by AlexanderPuzanov** [comment]
In an empty storage, when trying to activate the plugin.

app.js:1 Plugin failure: commentator RangeError: Field is not present in this state
    at e.field (app.js:1:288206)
    at e.update [as updateF] (VM144 plugin:commentator:18:156624)
    at Object.update (app.js:1:278210)
    at e.computeSlot (app.js:1:289060)
    at Ie (app.js:1:282154)
    at new e (app.js:1:288029)
    at e.applyTransaction (app.js:1:289015)
    at e.get (app.js:1:284158)
    at e.update (app.js:1:455893)
    at e.dispatchTransactions (app.js:1:453397)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
plugin:commentator:96 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'detachButtons')
    at Zl.onunload (plugin:commentator:96:30743)
    at Zl.unload (app.js:1:1214653)
    at e.<anonymous> (app.js:1:2271866)
    at app.js:1:248524
    at Object.next (app.js:1:248629)
    at app.js:1:247545
    at new Promise (<anonymous>)
    at g (app.js:1:247290)
    at e.unloadPlugin (app.js:1:2271728)
    at e.<anonymous> (app.js:1:2274736)
onunload @ plugin:commentator:96
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.unloadPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.disablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.disablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1

app.js:1 Plugin failure: commentator RangeError: Field is not present in this state
    at e.field (app.js:1:288206)
    at e.update [as updateF] (VM144 plugin:commentator:18:156624)
    at Object.update (app.js:1:278210)
    at e.computeSlot (app.js:1:289060)
    at Ie (app.js:1:282154)
    at new e (app.js:1:288029)
    at e.applyTransaction (app.js:1:289015)
    at e.get (app.js:1:284158)
    at e.update (app.js:1:455893)
    at e.dispatchTransactions (app.js:1:453397)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
plugin:commentator:96 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'detachButtons')
    at Zl.onunload (plugin:commentator:96:30743)
    at Zl.unload (app.js:1:1214653)
    at e.<anonymous> (app.js:1:2271866)
    at app.js:1:248524
    at Object.next (app.js:1:248629)
    at app.js:1:247545
    at new Promise (<anonymous>)
    at g (app.js:1:247290)
    at e.unloadPlugin (app.js:1:2271728)
    at e.<anonymous> (app.js:1:2274736)
onunload @ plugin:commentator:96
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.unloadPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.disablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.disablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
