### ISSUE TITLE
[BUG] Plugin does not start up on newer versions of Obsidian

### ISSUE THREAD

**Issue by SwordBlade1** [Fevol/obsidian-criticmarkup#23]
启动插件时立即自动关闭，已更新Obsidian最新版和插件0.26最新版。
![image](https://github.com/user-attachments/assets/bfcaf938-07a6-4c4a-b740-8daf7dfcea36)

**Comment by zhampu** [comment]
Having the same issue

**Comment by zhampu** [comment]
as a temporal solution I replaced this lines  in the main.ts file

`async onunload(){this.previewModeHeaderButton&&this.previewModeHeaderButton.detachButtons();this.editModeHeaderModeButton&&this.editModeHeaderModeButton.detachButtons();this.postProcessor&&qC.MarkdownPreviewRenderer.unregisterPostProcessor(this.postProcessor);for(let I of this.remove_monkeys)I();this.database&&this.database.unload();window.COMMENTATOR_DEBUG=void 0}
`

`detachButtons(){if(!this.changeEvent)return;for(let I of this.plugin.app.workspace.getLeavesOfType("markdown"))this.detachButton(I);this.plugin.app.workspace.offref(this.changeEvent);this.changeEvent=null}
`

**Comment by xmacex** [comment]
I too, unfortunately, fail to enable this very useful plugin. I am on Obsidian 1.7.7. It was working earlier this year.

```
app.js:1 Plugin failure: commentator TypeError: Cannot read properties of undefined (reading 'cm')
    at HF.eval [as getvalue] (plugin:commentator:14:172)
    at HF.attachButtons (plugin:commentator:11:114298)
    at HF.setRendering (plugin:commentator:11:113282)
    at new HF (plugin:commentator:11:113162)
    at mt (plugin:commentator:11:115231)
    at NQ.onload (plugin:commentator:39:3906167)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
e.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
g @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
plugin:commentator:39 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'detachButtons')
    at NQ.onunload (plugin:commentator:39:3907741)
    at e.unload (app.js:1:1230640)
    at e.<anonymous> (app.js:1:2199985)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at g (app.js:1:235994)
    at e.unloadPlugin (app.js:1:2199872)
    at e.<anonymous> (app.js:1:2203241)
```

If there is anything I can help with for reporting, triaging, testing or something, plase let me know!

@zhampu where did you make that change? I would be interested in a workaround until this gets fixed.

**Comment by Fevol** [comment]
Sorry everyone for the long wait! I will fix this as soon as possible.
The plugin's development has officially restarted, and more updates should follow soon.

**Comment by kerim** [comment]
Has this been fixed yet? I don't seem to be able to use the plugin...

**Comment by Fevol** [comment]
Apologies to everyone who has been waiting for an update. Due to personal circumstances, it has been difficult to get back to working on this plugin. 

The past few days, I did some spring cleaning on the codebase in order to get it working again with the latest version of Obsidian. Version [0.2.1](https://github.com/Fevol/obsidian-criticmarkup/releases/tag/0.2.1) is now available via BRAT. Aside from some bug fixes, it also includes live-preview rendering while editing comments.

There will very likely still be some major bugs, bear with me as I try to get all of them fixed (and add some much-needed features)!
